inherit_from: .rubocop_todo.yml

# 追加した規約ファイル読込
require:
  - rubocop-rails

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.6
  # 除外
  Exclude:
    - 'Gemfile'
    - 'bin/**'
    - 'db/schema.rb'
    - 'config/**/*'

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視
Style/FrozenStringLiteralComment:
  Enabled: false
  
# 条件式を`if-elsif`構文を` case-when`に置き換える必要性を無視  
Style/CaseLikeIf:  
  Enabled: false
  
# フィルターのオプションで指定されたメソッドの定義の必要性を無視 
Rails/LexicallyScopedActionFilter:
  Enabled: false
